import { policy } from "@/core/constants/common";
import { Legal } from "@/core/ui/layout/static/legal";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Policy",
  description: "Generated by create next app",
};
export default function StaticPages() {
  return <Legal data={policy} />;
}
