import { I_TableColumns, I_TableTicketData } from "@/interfaces";
import { MultiFilterType } from "@/types/admin/dashboard";

export const tableColumns: I_TableColumns[] = [
  {
    title: "Ticket",
    align: "left",
    width: "w-3/12",
  },
  {
    title: "Risk Level",
    align: "left",
    width: "w-2/12",
  },
  {
    title: "Vulnerability type (CWE)",
    align: "left",
    width: "w-3/12",
  },
  {
    title: "Rewards",
    align: "left",
    width: "w-1/12",
  },
  {
    title: "Status",
    align: "left",
    width: "w-2/12",
  },
  {
    title: "Last Update",
    align: "center",
    width: "w-1/12",
  },
];

export const tableTicketData: I_TableTicketData[] = [
  {
    ticket_number: "EX-001",
    title: "Example Corp",
    logo: "/images/company-logo/coinbase.png",
    date_reported: "2024-02-26",
    domain: "public",
    risk_level: "medium",
    vulnerability_type: "SQL Injection",
    rewards: 1000,
    status: "Open",
    update: "2024-02-26T08:30:00",
    is_new_notification: true,
  },
  {
    ticket_number: "PC-001",
    title: "Private Co.",
    logo: "/images/company-logo/coinbase.png",
    date_reported: "2024-02-25",
    domain: "private",
    risk_level: "high",
    vulnerability_type: "Cross-site Scripting (XSS)",
    rewards: 2500,
    status: "Closed",
    update: "2024-02-25T15:45:00",
    is_new_notification: true,
  },
  {
    ticket_number: "TL-001",
    title: "Test Ltd.",
    logo: "/images/company-logo/coinbase.png",
    date_reported: "2024-02-24",
    domain: "public",
    risk_level: "low",
    vulnerability_type: "Broken Authentication",
    rewards: 500,
    status: "Open",
    update: "2024-02-24T10:20:00",
    is_new_notification: false,
  },
  {
    ticket_number: "EX-002",
    title: "Example Corp",
    logo: "/images/company-logo/coinbase.png",
    date_reported: "2024-02-26",
    domain: "public",
    risk_level: "medium",
    vulnerability_type: "SQL Injection",
    rewards: 1000,
    status: "Open",
    update: "2024-02-26T08:30:00",
    is_new_notification: false,
  },
  {
    ticket_number: "PC-002",
    title: "Private Co.",
    logo: "/images/company-logo/coinbase.png",
    date_reported: "2024-02-25",
    domain: "private",
    risk_level: "high",
    vulnerability_type: "Cross-site Scripting (XSS)",
    rewards: 2500,
    status: "Closed",
    update: "2024-02-25T15:45:00",
    is_new_notification: false,
  },
  {
    ticket_number: "TL-002",
    title: "Test Ltd.",
    logo: "/images/company-logo/coinbase.png",
    date_reported: "2024-02-24",
    domain: "public",
    risk_level: "low",
    vulnerability_type: "Broken Authentication",
    rewards: 500,
    status: "Open",
    update: "2024-02-26T20:20:00",
    is_new_notification: false,
  },
];

export const filterItems: MultiFilterType = {
  risk_level: [
    { label: "All level", value: "all" },
    { label: "Low", value: "low" },
    { label: "Medium", value: "medium" },
    { label: "High", value: "high" },
    { label: "Critical", value: "critical" },
  ],
  type: [
    { label: "All type", value: "all" },
    { label: "Public", value: "public" },
    { label: "Private", value: "private" },
  ],
  status: [
    { label: "All status", value: "all" },
    { label: "Open", value: "Open" },
    { label: "In Review", value: "In Review" },
    { label: "Waiting for Payment", value: "Waiting for Payment" },
    { label: "Paid", value: "Paid" },
    { label: "Canceled", value: "Canceled" },
    { label: "Closed", value: "Closed" },
  ],
  company_status: [
    { label: "All status", value: "all" },
    { label: "Published", value: "Published" },
    { label: "Pending", value: "Pending" },
  ],
  asset_type: [
    { label: "All asset type", value: "all" },
    { label: "URL", value: "url" },
    { label: "Hardware/IOT", value: "iot" },
    { label: "Android: PlayStore", value: "android" },
    { label: "iOS:AppStore", value: "ios" },
  ],
};
