import { cn } from "@/core/lib/utils";
import { Header, Sidebar } from "@/core/ui/layout";
import { getSession } from "@/service/server/session";
import { Role } from "@/types/admin/sidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "VRP Launchpad",
  description: "Generated by create next app",
};

export default async function SettingsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();
  return (
    <>
      <div className="h-dvh w-full grid-cols-[auto_1fr] overflow-hidden xl:grid xl:h-screen">
        <Sidebar type={session?.user.role as keyof typeof Role} />
        <div
          className="_flexbox__col__start__start h-full w-full"
          suppressHydrationWarning
        >
          <Header />
          <div
            className={cn(
              "h-fit w-full overflow-auto xl:max-h-[calc(100vh-86px)]",
              "pt-0 xl:pl-14 xl:pr-12",
              "p-0"
            )}
          >
            {children}
          </div>
        </div>
      </div>
    </>
  );
}
