import { cn } from "@/core/lib/utils";
import { Desktop, Header, Mobile, Sidebar } from "@/core/ui/layout";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Companies",
  description: "Generated by create next app",
};

export default async function SettingsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Mobile>
        <div className="h-dvh w-full overflow-hidden">
          <Sidebar type={"mediator"} />
          <div
            className="_flexbox__col__start__start h-full w-full"
            suppressHydrationWarning
          >
            <Header />
            <div
              className={cn(
                "h-fit w-full overflow-auto xl:max-h-[calc(100vh-86px)]",
                "pt-0 xl:pb-28 xl:pl-14 xl:pr-12",
                "p-0"
              )}
            >
              {children}
            </div>
          </div>
        </div>
      </Mobile>
      <Desktop>
        <div className="grid h-screen w-full grid-cols-[auto_1fr] overflow-hidden">
          <Sidebar type={"mediator"} />
          <div
            className="_flexbox__col__start__start h-full w-full"
            suppressHydrationWarning
          >
            <Header />
            <div
              className={cn(
                "h-fit w-full overflow-auto xl:max-h-[calc(100vh-86px)]",
                "pt-0 xl:pb-28 xl:pl-14 xl:pr-12",
                "p-0"
              )}
            >
              {children}
            </div>
          </div>
        </div>
      </Desktop>
    </>
  );
}
