import { SignInFragment } from "@/feature/auth/Fragments";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sign In",
  description: "Generated by create next app",
};

const Login = () => {
  return <SignInFragment />;
};
export default Login;
