import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/core/ui/components/theme/theme-provider";
import { cn } from "@/core/lib/utils";
import Sidebar from "@/core/ui/layout/dashboard/Sidebar.layout";
import { getSession } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cybertise",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();

  const renderSidebar = () => {
    switch (session?.user.role) {
      case "hacker":
        return <Sidebar type={"hacker"} />;
      case "company":
        return <Sidebar type={"company"} />;
      case "mediator":
        return <Sidebar type={"mediator"} />;
      default:
        return null;
    }
  };

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          inter.className,
          "bg-background-page-light dark:bg-background-page-dark"
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          {session ? (
            <div className="grid h-screen w-full grid-cols-[auto_1fr] overflow-hidden">
              {renderSidebar()}
              {children}
            </div>
          ) : (
            <>{children}</>
          )}
        </ThemeProvider>
      </body>
    </html>
  );
}
