import { SignUpTypeFragment } from "@/feature/auth/Fragments";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sign Up",
  description: "Generated by create next app",
};

export default function Register() {
  return <SignUpTypeFragment />;
}
