import { AuthWrapper } from "@/core/ui/layout";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Forgot Password",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <AuthWrapper>{children}</AuthWrapper>;
}
