import { cn } from "@/core/lib/utils";
import { Desktop, Header, Mobile, Sidebar } from "@/core/ui/layout";
import { getSession } from "@/service/server/session";
import { UserType } from "@/types/auth/sign-up";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Reports",
  description: "Generated by create next app",
};

export default async function Dashboardlayout({
  hacker,
  company,
  mediator,
}: {
  children: React.ReactNode;
  hacker: React.ReactNode;
  company: React.ReactNode;
  mediator: React.ReactNode;
}) {
  const session = (await getSession()) as UserType;

  const child: { [key: string]: React.ReactNode } = {
    hacker: hacker,
    company: company,
    mediator: mediator,
    "company staff": company,
  };
  return (
    <>
      <Mobile>
        <div className="h-dvh w-full overflow-hidden">
          <Sidebar type={session?.user.role} />
          <div
            className="_flexbox__col__start__start h-full w-full"
            suppressHydrationWarning
          >
            <Header />
            <div
              className={cn(
                "h-fit w-full overflow-auto xl:max-h-[calc(100vh-86px)]",
                "pt-0 xl:pl-14 xl:pr-12",
                "p-0"
              )}
            >
              {child[session?.user.role]}
            </div>
            <div id="new-chat"></div>
          </div>
        </div>
      </Mobile>
      <Desktop>
        <div className="grid h-screen w-full grid-cols-[auto_1fr] overflow-hidden">
          <Sidebar type={session?.user.role} />
          <div
            className="_flexbox__col__start__start h-full w-full"
            suppressHydrationWarning
          >
            <Header />
            <div
              className={cn(
                "h-fit w-full overflow-auto xl:max-h-[calc(100vh-86px)]",
                "pt-0 xl:pl-14 xl:pr-12",
                "p-0"
              )}
            >
              {child[session?.user.role]}
            </div>
          </div>
        </div>
      </Desktop>
    </>
  );
}
