export { default as Dashboard } from "./dashboard/Dashboard.component";
export { default as Reports } from "./reports/Reports.component";
export { default as ReportDetails } from "./reports/details/ReportDetails.component";
export { default as VRPLaunchpad } from "./vrp-launcpad/VrpLaunchpad.component";
export { default as CreateVrp } from "./vrp-launcpad/create-vrp/CreateVrp.component";
export { default as Companies } from "./companies/Companies.component";
export { default as CompaniesDetail } from "./companies/details/CompaniesDetail.component";
export { default as NewCompanyReport } from "./reports/new/NewCompanyReport.component";
export { default as Statistics } from "./statistics/Statistics.component";
