import { cn } from "@/core/lib/utils";
import { Header, Sidebar } from "@/core/ui/layout";
import EmptyState from "@/core/ui/layout/empty-state/EmptyState.layout";
import { getSession } from "@/service/server/session";
import { UserType } from "@/types/auth/sign-up";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Programs",
  description: "Generated by create next app",
};

export default async function Dashboardlayout({
  hacker,
}: {
  children: React.ReactNode;
  hacker: React.ReactNode;
}) {
  const session = (await getSession()) as UserType;
  const child: { [key: string]: React.ReactNode } = {
    hacker: hacker,
    company: <EmptyState type="under-construction" variant="mediator" />,
    mediator: <EmptyState type="under-construction" variant="mediator" />,
  };

  return (
    <>
      <div className="w-full xl:hidden">
        <div className="h-dvh w-full overflow-hidden">
          <Sidebar type={session?.user.role} />
          <div className="_flexbox__col__start__start h-full w-full">
            <Header />
            <div
              className={cn(
                "h-fit w-full overflow-auto xl:max-h-[calc(100vh-86px)]",
                "pt-0 xl:pb-28 xl:pl-14 xl:pr-12",
                "p-0"
              )}
            >
              {child[session?.user.role]}
            </div>
          </div>
        </div>
      </div>
      <div className="hidden w-full xl:block">
        <div className="grid h-screen w-full grid-cols-[auto_1fr] overflow-hidden">
          <Sidebar type={session?.user.role} />
          <div className="_flexbox__col__start__start h-full w-full">
            <Header />
            <div
              className={cn(
                "h-fit w-full overflow-auto xl:max-h-[calc(100vh-86px)]",
                "pt-0 xl:pb-28 xl:pl-14 xl:pr-12",
                "p-0"
              )}
            >
              {child[session?.user.role]}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
