import { faqData } from "@/core/constants/common";
import { FaqLayout } from "@/core/ui/layout/static/faq";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "FAQ",
  description: "Generated by create next app",
};

export default function Faq() {
  return <FaqLayout data={faqData} />;
}
